### ISSUE TITLE
Optional object properties

### ISSUE THREAD

**Issue by jamiehodge** [gcanti/flow-io#24]
What is the intended approach to validating?

```javascript
type Foo = {
  bar: string,
  baz?: number,
  qux?: boolean
}
```

I can see that a union of permutations would cover it, but is there something more elegant?

**Comment by gcanti** [comment]
In theory

```js
type Foo = {
  foo?: string
}
```

and 

```js
type Foo = {
  foo: string | void
}
```

are not the same thing, but in practice while validating IO (for example an API payload) are any different? 

I wonder because AFAIK there's no way to encode optional fields like `foo?` using Flow features. Relevant code here https://github.com/gcanti/flow-io/blob/master/src/index.js#L546

**Comment by jamiehodge** [comment]
This is the feature I'm referring to: https://flowtype.org/docs/objects.html#optional-properties

**Comment by gcanti** [comment]
Yes, but I don't know how to implement such a behaviour using `$ObjMap` (see the link above) and, in practice, I wonder if it really matters from the point of view of IO validation

**Comment by jamiehodge** [comment]
Fair enough. Let's close this. I didn't realise that the two were equivalent. Thank you!
